### ISSUE TITLE
Error opening file

### ISSUE THREAD

**Issue by totytremendo** [seongland/pointland#102]
![image](https://user-images.githubusercontent.com/85905110/121956945-1c348a00-cd38-11eb-9399-50333e5420c6.png)
file:///content/drive/My Drive/Copia de Red Pío IX.xlsx.gsheet": [Errno 95] Operation not supported. ¿porque no puede copiar archivos tipo .gsheet o gdoc?

**Comment by seonglae** [comment]
I have no idea about your issue. Do you misplaced this issue with another repo?

**Comment by seonglae** [comment]
Long time no response!
